export const SET_CONTRACT_TYPE = 'SET_CONTRACT_TYPE';
export const SET_CONTACT_METHOD = 'SET_CONTACT_METHOD';
export const SET_CONTACT_EMAIL = 'SET_CONTACT_EMAIL';
export const SET_CONTACT_PHONE = 'SET_CONTACT_PHONE';
export const SET_AMOUNT = 'SET_AMOUNT';
export const SET_TERMS_AND_CONDITIONS = 'SET_TERMS_AND_CONDITIONS';
export const SET_SUBSCRIBE_TO_NEWSLETTER = 'SET_SUBSCRIBE_TO_NEWSLETTER';
